// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrabajoPracticoN2BlazorServerYBasesDeDatos.Data;

#nullable disable

namespace TrabajoPracticoN2BlazorServerYBasesDeDatos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrabajoPracticoN2BlazorServerYBasesDeDatos.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Gómez",
                            Email = "laura.gomez@email.com",
                            Nombre = "Laura",
                            Telefono = "2954-15223344"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Martínez",
                            Email = "sofia.m@email.com",
                            Nombre = "Sofía",
                            Telefono = "2954-15667788"
                        });
                });

            modelBuilder.Entity("TrabajoPracticoN2BlazorServerYBasesDeDatos.Models.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Servicios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Incluye extracción y máscara hidratante",
                            Nombre = "Limpieza Facial",
                            Precio = 15000.00m
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Sesión de 45 minutos",
                            Nombre = "Masaje Descontracturante",
                            Precio = 12000.00m
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Esmaltado de larga duración",
                            Nombre = "Manicura Semipermanente",
                            Precio = 8500.00m
                        });
                });

            modelBuilder.Entity("TrabajoPracticoN2BlazorServerYBasesDeDatos.Models.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServicioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ServicioId");

                    b.ToTable("Turnos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteId = 1,
                            FechaHora = new DateTime(2026, 10, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Observaciones = "Primera visita al centro",
                            ServicioId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClienteId = 2,
                            FechaHora = new DateTime(2026, 10, 15, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            Observaciones = "",
                            ServicioId = 3
                        });
                });

            modelBuilder.Entity("TrabajoPracticoN2BlazorServerYBasesDeDatos.Models.Turno", b =>
                {
                    b.HasOne("TrabajoPracticoN2BlazorServerYBasesDeDatos.Models.Cliente", "Cliente")
                        .WithMany("Turnos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrabajoPracticoN2BlazorServerYBasesDeDatos.Models.Servicio", "Servicio")
                        .WithMany("Turnos")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("TrabajoPracticoN2BlazorServerYBasesDeDatos.Models.Cliente", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("TrabajoPracticoN2BlazorServerYBasesDeDatos.Models.Servicio", b =>
                {
                    b.Navigation("Turnos");
                });
#pragma warning restore 612, 618
        }
    }
}
